# Obtención y  remuestreo de datos sobre criptomonedas

In [1]:
import requests
import pandas as pd

#Consulta con la API Kraken en este caso datos de Ethereum
endpoint = 'https://api.kraken.com/0/public/Trades'
payLoad = {'pair': 'XETHZUSD'}
response = requests.get(url=endpoint, params=payLoad)
tradeData = response.json()
trades = tradeData['result']['XETHZUSD']
#Ver las 5 primeras operaciones
trades[:5]

[['2338.74000', '3.25593449', 1773772490.388754, 's', 'l', '', 61534507],
 ['2338.74000', '8.37606551', 1773772490.388754, 's', 'l', '', 61534508],
 ['2338.63000', '0.47940150', 1773772490.388754, 's', 'l', '', 61534509],
 ['2338.63000', '0.64327297', 1773772490.388754, 's', 'l', '', 61534510],
 ['2338.63000', '0.85775247', 1773772490.3887541, 's', 'l', '', 61534511]]

In [2]:
#Crear del dataframe,por defecto las 1000 últimas operaciones
tradesDF = pd.DataFrame.from_records(trades,                                    
columns=['Precio','Volumen','Tiempo','Compra/Venta','Mercado/Orden Límite','Misc','DUMMY'])
tradesDF = tradesDF.drop(columns=['DUMMY']) 
tradesDF

,Precio,Volumen,Tiempo,Compra/Venta,Mercado/Orden Límite,Misc
0,2338.74000,3.25593449,1.773772e+09,s,l,
1,2338.74000,8.37606551,1.773772e+09,s,l,
2,2338.63000,0.47940150,1.773772e+09,s,l,
3,2338.63000,0.64327297,1.773772e+09,s,l,
4,2338.63000,0.85775247,1.773772e+09,s,l,
...,...,...,...,...,...,...
995,2331.74000,7.50231503,1.773776e+09,b,l,
996,2331.74000,0.46237384,1.773776e+09,b,l,
997,2331.74000,9.45478063,1.773776e+09,b,l,
998,2331.74000,0.00348744,1.773776e+09,b,l,
999,2331.77000,21.43500000,1.773776e+09,b,l,

In [3]:
#Crear el indice de tiempo en formato fecha y hora
tradesDF['Tiempo'] = pd.to_datetime(tradesDF['Tiempo'], unit='s')
tradesDF.set_index('Tiempo',inplace=True)
tradesDF

,Precio,Volumen,Compra/Venta,Mercado/Orden Límite,Misc
Tiempo,,,,,
2026-03-17 18:34:50.388753891,2338.74000,3.25593449,s,l,
2026-03-17 18:34:50.388753891,2338.74000,8.37606551,s,l,
2026-03-17 18:34:50.388753891,2338.63000,0.47940150,s,l,
2026-03-17 18:34:50.388753891,2338.63000,0.64327297,s,l,
2026-03-17 18:34:50.388754129,2338.63000,0.85775247,s,l,
...,...,...,...,...,...
2026-03-17 19:32:58.670274496,2331.74000,7.50231503,b,l,
2026-03-17 19:32:58.670274496,2331.74000,0.46237384,b,l,
2026-03-17 19:32:58.670274496,2331.74000,9.45478063,b,l,
2026-03-17 19:32:58.670274496,2331.74000,0.00348744,b,l,
2026-03-17 19:32:58.670274496,2331.77000,21.43500000,b,l,

In [4]:
#consultar la última marca de tiempo
tradeData["result"]["last"]

'1773775978670274466'

In [5]:
pd.to_datetime(int(tradeData["result"]["last"]),unit="ns")

Timestamp('2026-03-17 19:32:58.670274466')

In [6]:
#Remuestreo por minutos
tradesDF.resample('1min')['Precio'].agg(['first'])

                          first
Tiempo
2026-03-17 18:34:00  2338.74000
2026-03-17 18:35:00  2338.00000
2026-03-17 18:36:00  2339.11000
2026-03-17 18:37:00  2340.07000
2026-03-17 18:38:00  2339.24000
2026-03-17 18:39:00  2339.85000
2026-03-17 18:40:00  2340.50000
2026-03-17 18:41:00  2340.29000
2026-03-17 18:42:00  2340.01000
2026-03-17 18:43:00  2340.01000
2026-03-17 18:44:00  2340.00000
2026-03-17 18:45:00  2337.93000
2026-03-17 18:46:00  2339.66000
2026-03-17 18:47:00  2339.01000
2026-03-17 18:48:00  2338.98000
2026-03-17 18:49:00  2338.98000
2026-03-17 18:50:00  2338.22000
2026-03-17 18:51:00  2337.26000
2026-03-17 18:52:00  2336.75000
2026-03-17 18:53:00  2336.00000
2026-03-17 18:54:00  2336.22000
2026-03-17 18:55:00  2336.08000
2026-03-17 18:56:00  2331.50000
2026-03-17 18:57:00  2331.89000
2026-03-17 18:58:00  2331.94000
2026-03-17 18:59:00  2333.01000
2026-03-17 19:00:00  2333.81000
2026-03-17 19:01:00  2332.60000
2026-03-17 19:02:00  2335.30000
2026-03-17 19:03:00  2333.99000
2026-03-17 19:04:00  2333.28000
2026-03-17 19:05:00  2334.00000
2026-03-17 19:06:00  2334.78000
2026-03-17 19:07:00  2334.19000
2026-03-17 19:08:00  2335.08000
2026-03-17 19:09:00  2336.63000
2026-03-17 19:10:00  2335.89000
2026-03-17 19:11:00  2337.95000
2026-03-17 19:12:00  2339.50000
2026-03-17 19:13:00  2339.27000
2026-03-17 19:14:00  2338.72000
2026-03-17 19:15:00  2338.26000
2026-03-17 19:16:00  2340.00000
2026-03-17 19:17:00  2339.99000
2026-03-17 19:18:00  2339.30000
2026-03-17 19:19:00  2339.64000
2026-03-17 19:20:00  2338.97000
2026-03-17 19:21:00  2337.41000
2026-03-17 19:22:00  2337.95000
2026-03-17 19:23:00  2337.24000
2026-03-17 19:24:00  2336.12000
2026-03-17 19:25:00  2338.66000
2026-03-17 19:26:00  2337.27000
2026-03-17 19:27:00  2336.61000
2026-03-17 19:28:00  2335.31000
2026-03-17 19:29:00  2334.78000
2026-03-17 19:30:00  2335.16000
2026-03-17 19:31:00  2334.01000
2026-03-17 19:32:00  2332.75000

In [8]:
#Obtener dos ohlc: Open ,High,Low y Close
ohlc = tradesDF.resample("1min", label="left")["Precio"].agg(["first","max","min","last"])
ohlc.columns = ["Open","High","Low","Close"]

In [9]:
ohlc

                           Open        High         Low       Close
Tiempo
2026-03-17 18:34:00  2338.74000  2338.74000  2338.00000  2338.00000
2026-03-17 18:35:00  2338.00000  2339.00000  2337.99000  2339.00000
2026-03-17 18:36:00  2339.11000  2340.80000  2339.11000  2339.77000
2026-03-17 18:37:00  2340.07000  2340.09000  2339.34000  2339.46000
2026-03-17 18:38:00  2339.24000  2339.66000  2338.52000  2339.59000
2026-03-17 18:39:00  2339.85000  2342.00000  2339.85000  2340.70000
2026-03-17 18:40:00  2340.50000  2341.16000  2340.01000  2341.14000
2026-03-17 18:41:00  2340.29000  2340.29000  2340.00000  2340.00000
2026-03-17 18:42:00  2340.01000  2340.78000  2340.01000  2340.01000
2026-03-17 18:43:00  2340.01000  2340.97000  2340.01000  2340.54000
2026-03-17 18:44:00  2340.00000  2340.00000  2337.86000  2337.86000
2026-03-17 18:45:00  2337.93000  2339.94000  2337.70000  2339.45000
2026-03-17 18:46:00  2339.66000  2339.95000  2339.18000  2339.34000
2026-03-17 18:47:00  2339.01000  2339.41000  2338.01000  2339.39000
2026-03-17 18:48:00  2338.98000  2338.99000  2338.42000  2338.70000
2026-03-17 18:49:00  2338.98000  2338.98000  2338.36000  2338.50000
2026-03-17 18:50:00  2338.22000  2338.29000  2337.43000  2337.64000
2026-03-17 18:51:00  2337.26000  2337.37000  2336.95000  2336.95000
2026-03-17 18:52:00  2336.75000  2337.00000  2336.01000  2336.45000
2026-03-17 18:53:00  2336.00000  2336.78000  2335.00000  2336.45000
2026-03-17 18:54:00  2336.22000  2336.42000  2335.55000  2336.08000
2026-03-17 18:55:00  2336.08000  2336.08000  2331.00000  2331.47000
2026-03-17 18:56:00  2331.50000  2331.51000  2329.30000  2330.59000
2026-03-17 18:57:00  2331.89000  2332.76000  2331.89000  2332.43000
2026-03-17 18:58:00  2331.94000  2332.87000  2331.94000  2332.73000
2026-03-17 18:59:00  2333.01000  2333.83000  2333.01000  2333.83000
2026-03-17 19:00:00  2333.81000  2333.81000  2332.20000  2332.21000
2026-03-17 19:01:00  2332.60000  2334.79000  2332.60000  2334.79000
2026-03-17 19:02:00  2335.30000  2336.12000  2334.25000  2334.25000
2026-03-17 19:03:00  2333.99000  2334.00000  2333.05000  2333.54000
2026-03-17 19:04:00  2333.28000  2334.01000  2333.28000  2334.01000
2026-03-17 19:05:00  2334.00000  2334.15000  2334.00000  2334.15000
2026-03-17 19:06:00  2334.78000  2335.07000  2334.00000  2334.00000
2026-03-17 19:07:00  2334.19000  2334.29000  2334.00000  2334.00000
2026-03-17 19:08:00  2335.08000  2335.77000  2334.78000  2335.16000
2026-03-17 19:09:00  2336.63000  2336.87000  2335.16000  2335.68000
2026-03-17 19:10:00  2335.89000  2337.95000  2335.88000  2337.95000
2026-03-17 19:11:00  2337.95000  2338.72000  2337.95000  2338.72000
2026-03-17 19:12:00  2339.50000  2339.56000  2339.27000  2339.28000
2026-03-17 19:13:00  2339.27000  2339.27000  2338.31000  2338.56000
2026-03-17 19:14:00  2338.72000  2338.72000  2338.04000  2338.22000
2026-03-17 19:15:00  2338.26000  2340.00000  2338.26000  2340.00000
2026-03-17 19:16:00  2340.00000  2340.00000  2339.49000  2340.00000
2026-03-17 19:17:00  2339.99000  2340.00000  2338.79000  2339.82000
2026-03-17 19:18:00  2339.30000  2339.83000  2339.30000  2339.81000
2026-03-17 19:19:00  2339.64000  2340.00000  2339.56000  2339.61000
2026-03-17 19:20:00  2338.97000  2338.97000  2335.26000  2336.68000
2026-03-17 19:21:00  2337.41000  2338.21000  2337.41000  2338.15000
2026-03-17 19:22:00  2337.95000  2339.68000  2337.28000  2337.28000
2026-03-17 19:23:00  2337.24000  2337.44000  2335.17000  2335.70000
2026-03-17 19:24:00  2336.12000  2337.53000  2336.12000  2337.39000
2026-03-17 19:25:00  2338.66000  2338.66000  2337.66000  2337.66000
2026-03-17 19:26:00  2337.27000  2337.27000  2336.29000  2336.66000
2026-03-17 19:27:00  2336.61000  2336.82000  2335.81000  2335.81000
2026-03-17 19:28:00  2335.31000  2335.31000  2333.83000  2334.77000
2026-03-17 19:29:00  2334.78000  2335.17000  2334.78000  2335.17000
2026-03-17 19:30:00  2335.16000  2335.17000  2334.02000  2334.02000
2026-03-17 19:31:00  2334.01000  2334.01000  2332.31000  2332.74000
2026-03-17 19:32:00  2332.75000  2333.06000  2331.74000  2331.77000

## Ejemplo con función

In [10]:

import requests
import pandas as pd
import datetime
from datetime import timezone
import time

def getKrakenTradeData(pair, startDate, endDate):
    endpoint = 'https://api.kraken.com/0/public/Trades'
    
    startTime = int(datetime.datetime.strptime(startDate, '%Y-%m-%d').replace(tzinfo=timezone.utc).timestamp()*1000000000)
    endTime =   int(datetime.datetime.strptime(endDate, '%Y-%m-%d').replace(tzinfo=timezone.utc).timestamp()*1000000000)
    
    timeLoaded = startTime
    
    result = pd.DataFrame()
    
    while timeLoaded < endTime:
        print(pd.to_datetime(timeLoaded, unit='ns').strftime('%Y-%m-%d %H:%M:%S'))
        payLoad = {'pair': pair,
                   'since': timeLoaded}
        
        response = requests.get(url=endpoint, params=payLoad)
        data = response.json()['result']
        tradesRaw = data[pair]
        timeLoaded = int(data["last"])
        
        tradeData = pd.DataFrame.from_records(tradesRaw,
                             columns=['Price', 'Volume', 'Time', 'BuySell', 'MarketLimit', 'Misc','DUMMY'])
        tradeData['Time'] = pd.to_datetime(tradeData['Time'], unit='s')
        
        result = pd.concat([result, tradeData])
        
        time.sleep(5)
        
    result.set_index("Time", inplace = True)
    result = result.loc[startDate:endDate+' 00:00:00']
    
    return result

### Utilizando la función , en este caso bitcoin con unas fechas especificas

In [32]:
df = getKrakenTradeData(
        pair="XXBTZUSD",
        startDate="2026-03-11",
        endDate="2026-03-12"
     )
df = df.drop(columns=['DUMMY']) 
df.tail(10)

2026-03-11 00:00:00
2026-03-11 00:17:24
2026-03-11 00:40:02
2026-03-11 01:14:48
2026-03-11 01:47:45
2026-03-11 02:23:24
2026-03-11 02:49:04
2026-03-11 03:21:21
2026-03-11 04:00:56
2026-03-11 04:33:50
2026-03-11 05:17:42
2026-03-11 05:46:27
2026-03-11 06:21:11
2026-03-11 07:05:10
2026-03-11 07:50:50
2026-03-11 08:35:01
2026-03-11 09:04:57
2026-03-11 09:40:13
2026-03-11 10:14:57
2026-03-11 11:00:44
2026-03-11 11:39:13
2026-03-11 11:59:51
2026-03-11 12:12:46
2026-03-11 12:30:12
2026-03-11 12:49:39
2026-03-11 13:13:57
2026-03-11 13:20:07
2026-03-11 13:31:12
2026-03-11 13:38:02
2026-03-11 13:45:07
2026-03-11 13:52:57
2026-03-11 14:00:59
2026-03-11 14:07:17
2026-03-11 14:15:42
2026-03-11 14:27:24
2026-03-11 14:38:44
2026-03-11 14:51:38
2026-03-11 15:06:06
2026-03-11 15:17:09
2026-03-11 15:31:10
2026-03-11 15:45:03
2026-03-11 16:01:03
2026-03-11 16:11:55
2026-03-11 16:27:40
2026-03-11 16:44:40
2026-03-11 17:01:07
2026-03-11 17:13:50
2026-03-11 17:23:42
2026-03-11 17:30:49
2026-03-11 17:39:29
2026-03-11 17:54:32
2026-03-11 18:12:39
2026-03-11 18:33:29
2026-03-11 18:53:11
2026-03-11 19:14:27
2026-03-11 19:43:18
2026-03-11 20:11:00
2026-03-11 20:43:32
2026-03-11 21:06:25
2026-03-11 21:34:07
2026-03-11 22:02:37
2026-03-11 22:26:32
2026-03-11 22:44:38
2026-03-11 23:03:24
2026-03-11 23:33:34
2026-03-11 23:49:55

,Price,Volume,BuySell,MarketLimit,Misc
Time,,,,,
2026-03-11 23:59:34.932181358,70200.40000,0.00013864,b,l,
2026-03-11 23:59:50.419239759,70200.30000,0.00056000,s,l,
2026-03-11 23:59:55.885238409,70200.40000,0.00021156,b,l,
2026-03-12 00:00:00.093214273,70200.40000,0.00064980,b,l,
2026-03-12 00:00:00.093214273,70200.40000,0.00005192,b,l,
2026-03-12 00:00:00.124227524,70200.40000,0.00013964,b,l,
2026-03-12 00:00:00.148654461,70200.40000,0.00021262,b,l,
2026-03-12 00:00:00.159912825,70200.40000,0.00070519,b,l,
2026-03-12 00:00:00.343577147,70200.40000,0.00035086,b,l,
2026-03-12 00:00:00.347683430,70200.40000,0.00014139,b,l,

In [35]:
#Remuestreo en horas
df.resample('1h')['Price'].agg(['first'])

                           first
Time
2026-03-11 00:00:00  69955.40000
2026-03-11 01:00:00  70052.10000
2026-03-11 02:00:00  70084.50000
2026-03-11 03:00:00  69812.00000
2026-03-11 04:00:00  69567.70000
2026-03-11 05:00:00  70133.20000
2026-03-11 06:00:00  69512.20000
2026-03-11 07:00:00  69955.00000
2026-03-11 08:00:00  69647.10000
2026-03-11 09:00:00  69664.60000
2026-03-11 10:00:00  69463.90000
2026-03-11 11:00:00  69610.10000
2026-03-11 12:00:00  69175.60000
2026-03-11 13:00:00  69362.10000
2026-03-11 14:00:00  70187.70000
2026-03-11 15:00:00  70573.80000
2026-03-11 16:00:00  70253.10000
2026-03-11 17:00:00  70570.00000
2026-03-11 18:00:00  70801.10000
2026-03-11 19:00:00  70640.70000
2026-03-11 20:00:00  70674.10000
2026-03-11 21:00:00  70634.40000
2026-03-11 22:00:00  70762.10000
2026-03-11 23:00:00  70366.60000
2026-03-12 00:00:00  70200.40000

In [37]:
# Obtener los datos OHLC: Open,High,Low,Close
ohlc = df.resample("1h", label="left")["Price"].agg(["first","max","min","last"])
ohlc.columns = ["Open","High","Low","Close"]
ohlc

                            Open         High          Low        Close
Time
2026-03-11 00:00:00  69955.40000  70165.20000  69782.10000  70052.10000
2026-03-11 01:00:00  70052.10000  70138.60000  69902.10000  70084.40000
2026-03-11 02:00:00  70084.50000  70121.90000  69644.80000  69803.70000
2026-03-11 03:00:00  69812.00000  69887.00000  69517.10000  69567.60000
2026-03-11 04:00:00  69567.70000  70251.80000  69519.80000  70154.50000
2026-03-11 05:00:00  70133.20000  70186.90000  69450.00000  69512.10000
2026-03-11 06:00:00  69512.20000  69985.30000  69512.10000  69955.00000
2026-03-11 07:00:00  69955.00000  70012.40000  69512.40000  69649.20000
2026-03-11 08:00:00  69647.10000  69793.80000  69512.10000  69665.10000
2026-03-11 09:00:00  69664.60000  69737.00000  69387.10000  69452.00000
2026-03-11 10:00:00  69463.90000  69712.50000  69403.80000  69610.10000
2026-03-11 11:00:00  69610.10000  69663.50000  69155.90000  69174.40000
2026-03-11 12:00:00  69175.60000  69795.50000  68971.60000  69362.10000
2026-03-11 13:00:00  69362.10000  71083.30000  69360.30000  70187.60000
2026-03-11 14:00:00  70187.70000  70986.30000  69942.90000  70566.50000
2026-03-11 15:00:00  70573.80000  70652.00000  69707.10000  70242.80000
2026-03-11 16:00:00  70253.10000  70842.10000  70183.70000  70570.00000
2026-03-11 17:00:00  70570.00000  71345.20000  70524.10000  70780.20000
2026-03-11 18:00:00  70801.10000  70892.90000  70463.40000  70640.80000
2026-03-11 19:00:00  70640.70000  70747.60000  70405.30000  70674.10000
2026-03-11 20:00:00  70674.10000  70713.00000  70408.60000  70634.30000
2026-03-11 21:00:00  70634.40000  70780.00000  70517.90000  70762.10000
2026-03-11 22:00:00  70762.10000  70935.50000  70270.10000  70366.60000
2026-03-11 23:00:00  70366.60000  70500.00000  70148.00000  70200.40000
2026-03-12 00:00:00  70200.40000  70200.40000  70200.40000  70200.40000